initial settings
711skhu/process pull request #1
Opened 2019-05-02 13:35 UTC by lwiiiiii

2019-05-02 13:36 UTC, yjll1019 approved these changes

2019-05-02 13:37 UTC, KimJye approved these changes

2019-05-02 13:38 UTC, shouwn requested changes
JavaRunner 클래스와 Runner 인터페이스가 최상위에 위치하네요

하나의 패키지를 만들어서 거기에 위치시켜놓는 게 좋을 것이라 생각합니다.

2019-05-04 05:56 UTC, shouwn approved these changes

2019-05-04 10:36 UTC, merged